### ISSUE TITLE
Abuse spinner height TS1

### ISSUE THREAD

**Issue by dccsimrik** [DigitalCyberCherries/Hypercharge-Unboxed#16]
I could "abuse" the height of the spinners targeting me in TS1. they try to kill me, but im standing to high for them. Was easy for me to kill all of them.
So maybe lower Spinner targeting or maybe changing height of this part in the level (unless its on purpose).

![image](https://user-images.githubusercontent.com/29632110/27481860-33d835a4-581f-11e7-9a5e-944c14d30527.png)
![image](https://user-images.githubusercontent.com/29632110/27481864-3995272c-581f-11e7-8dbf-e7038ef7a6f1.png)

**Comment by Creekmonster** [comment]
Yeah, it's on purpose of course. If you didn't stand on that box, you could stand on any of the other million boxes.. we can't have spinners flying up onto shelves to kill players. When you're on the ground, they're chasing you and not the core, but you're in the dangerzone. Being out of their territory makes them focus the core more, it's a balance I think works with the current state of the game
