### ISSUE TITLE
Destroyed turret base not completely destroyed (??)

### ISSUE THREAD

**Issue by ghost** [DigitalCyberCherries/Hypercharge-Unboxed#18]
I'm not exactly sure what caused this to happen, but if I had to guess, the airplane managed to land a shot on the turret right as I killed it and something managed to break along the way.  The healing turret was still perfectly functional, but I noticed that I could build a base on top of it.  I neglected to see if I could build another turret and have them overlap.

Outside of Buildmode:
![20170623185759_1](https://user-images.githubusercontent.com/29635223/27503020-a2658176-5846-11e7-900d-aca092ddec04.jpg)

During Buildmode:
![20170623185801_1](https://user-images.githubusercontent.com/29635223/27503026-afb0e7a8-5846-11e7-9452-6f232910892c.jpg)

**Comment by Dec1234** [comment]
They have 5000 health, i guess that was not enough, haha. bCanBeDamaged has been disabled on these bases.
